### ISSUE TITLE
Seems broken on new Pulsar installation

### ISSUE THREAD

**Issue by HeroesLament** [mschuchard/linter-packer-validate#5]
Hello guys,

So upon installing to the new Pulsar build of Atom, it seems to not call "packer validate" on the pkr.hcl file anymore. Any ideas where to start troubleshooting?

Thank you,

**Comment by mschuchard** [comment]
Although not mentioned yet in the documentation: this package is unit tested against Atom 1.61.0-beta, and acceptance tested against Atom 1.63.0-dev. Pulsar is very slightly ahead of that dev version of Atom, and may have changed how it handled packages due to naming/copyright/apm discontinuation/etc. issues. Documentation is still being written for Pulsar, and its development is also very much still in flux.

Once Pulsar officially releases stable WRT packages I can acceptance test against it, but for now this package is unit tested against the final beta of official Atom and acceptance tested against the final dev of community Atom.

**Comment by mschuchard** [comment]
Forgot to close as this is already on roadmap for when Pulsar releases.
